# Generated by Django 5.2.17 on 2026-09-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_contact_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Файл прайса'),
        ),
    ]
